# Generated by Django 5.1.6 on 2025-02-17 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataHorario', models.DateTimeField()),
                ('nomeCliente', models.CharField(max_length=200)),
                ('emailCliente', models.EmailField(max_length=254)),
                ('telefoneCliente', models.CharField(max_length=20)),
            ],
        ),
    ]
